spring:
  application:
    name: gateway
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_db
    username: parviz
    password: qwerty

grpc:
  client:
    user-service:
      address: static://localhost:9090
      negotiationType: PLAINTEXT
