spring:
  application:
    name: cash.operation.service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cash_operation_db
    username: parviz
    password: qwerty

server:
  port: 8084